name: Load Test

on:
  workflow_dispatch:

jobs:
  load-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Run Load Test
        run: |
          k6 run tests/load-test/get-user-env.js --env STAGES_SET='[{"duration":"5s","target":10},{"duration":"10s","target":10},{"duration":"5s","target":0}]'

      - name: Prepare and Upload Report
        run: |
          mkdir -p public
          cp summary.html public/

      - name: Upload Report
        uses: actions/upload-artifact@v4.3.5
        with:
          name: Load Test Report
          path: public/summary.html
