name: E2E/UI Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5.2.0

        with:
          python-version: 3.10.12

      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Browser Init
        run: rfbrowser init

      - name: Run E2E Tests
        run: robot -d ./logs -v BROWSER:chromium -v IS_HEADLESS:True tests

      - name: Robot Report
        uses: joonvena/robotframework-reporter-action@v2.4
        if: always()

        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: logs

      - name: Upload Report
        uses: actions/upload-artifact@v4.3.5
        with:
          name: Test Report Chromium
          path: logs

      - name: Prepare artifacts for GitHub Pages
        run: |
          mkdir public
          cp -r logs/* public/
          mv public/report.html public/index.html

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
